import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React, { useEffect, useState } from "react";
import carsApi from "./api/carsApi";
import Link from 'next/link'

export default function Home() {

  const [carsRegistered, setCarsRegistred] = useState([]);

  const deleteCar = async (carId) => {
    await carsApi.delete(`/car/${carId}`)
    .then((response) => location.reload())
    .catch((err) => {
        alert(err)
    })

  }

  useEffect(() => {
    carsApi.get("/car")
      .then((response) => {
        setCarsRegistred(response.data)
      })
      .catch((err) => {
        console.error("ops! ocorreu um erro" + err);
      });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Cars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <h1 className={styles.title}>
          Welcome to <a href="https://www.linkedin.com/in/caiolucenacolaco/">Car's Front!</a>
        </h1>

        <p className={styles.description}>
          <Link href='/'>
            <button className={styles.btn_window}>Home</button>
          </Link>

          <Link href='/register'>
            <button className={styles.btn_window}>Register Cars</button>
          </Link>
        </p>

        <div className={styles.grid}>

            {carsRegistered.map(car => {
                return (
                  <div key={car.id} className={styles.card}>
                    <div>
                      <div className={styles.card_header}>
                        <h2>{car.model}</h2>
                      </div>

                        <p className={styles.card_content}>Cor: {car.color}</p>
                        <p className={styles.card_content}>Marca: {car.marca}</p>
                        <p className={styles.card_content}>Modelo: {car.yearFabrication}</p>
                        <p className={styles.card_content}>Fabricação: {car.yearModel }</p>
                    </div>
                    <button onClick={() => deleteCar(car.id)} className={styles.card_delete}>Delete</button>
                  </div>
                )
            })}

        </div>

      </main>

      <footer className={styles.footer}>
          Powered by{' '}
          <span className={styles.logo}>
            Caio Lucena Colaço
          </span>
      
      </footer>
    </div>
  )
}
