import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://www.linkedin.com/in/caiolucenacolaco/">Car's Front!</a>
        </h1>

        <p className={styles.description}>
          O que você deseja?
        </p>

        <div className={styles.grid}>

          <a href="/register" className={styles.card}>
            <h2>Registrar &rarr;</h2>
            <p>Faça o registro de um carro novo!</p>
          </a>

          <a href="/cars" className={styles.card}>
            <h2>Carros &rarr;</h2>
            <p>Veja aqui quais carros já estão registrados!</p>
          </a>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.linkedin.com/in/caiolucenacolaco/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            Caio Lucena Colaço
          </span>
        </a>
      </footer>
    </div>
  )
}
